# k8s/overlays/dev/deployment-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1  # Only changing the number of replicas for dev
  template:
    spec:
      containers:
      - name: webapp
        image: jfechava/web-sample:2.0.0  # Only changing the image
