apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-argo-application-qa
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jfechava/argocd-kustomize-web.git 
    targetRevision: HEAD
    path: web-app-argo/overlays/qa
  destination: 
    server: https://kubernetes.default.svc
    namespace: webapp-qa

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
