apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: jfechava/web-sample:3.0.0
        resources: 
            limits:
              memory: 300mi
              cpu: 400 mi
        ports:
        - containerPort: 80